name: Build and Deploy Storybook

on:
  push:
    branches: [main]
    paths:
      - 'ui/**'
      - '.github/workflows/deploy-storybook.yml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./ui

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: ./ui

      # Option 1: Deploy to GitHub Pages (if you have it enabled)
      - name: Deploy to GitHub Pages (optional)
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui/storybook-static
          destination_dir: storybook

      # Option 2: Commit the build for Deno Deploy
      - name: Commit Storybook build for Deno Deploy
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Remove storybook-static from .gitignore temporarily
          sed -i '/storybook-static/d' ui/.gitignore

          # Add and commit the built files
          git add ui/storybook-static -f
          git diff --staged --quiet || git commit -m "Build: Storybook static files [skip ci]"

          # Push to a separate branch for deployments
          git push origin HEAD:storybook-build --force
        if: github.ref == 'refs/heads/main'