name: Deploy All (Storybook then Deno)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./ui

      - name: Build Storybook
        run: npm run build-storybook
        working-directory: ./ui

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: ui/storybook-static
          retention-days: 1

  deploy-to-deno:
    needs: build-storybook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Storybook build
        uses: actions/download-artifact@v4
        with:
          name: storybook-static
          path: ui/storybook-static

      - name: Trigger Deno Deploy
        run: |
          echo "Storybook build complete, ready for Deno Deploy"
          # Deno Deploy will automatically pick up this push

      # Optional: If you want to commit the build to the repo
      # - name: Commit build artifacts
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add ui/storybook-static -f
      #     git diff --staged --quiet || git commit -m "Build: Updated Storybook [skip ci]"
      #     git push